on: push

name: deploy production
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: ðŸ“‚ Sync files
        uses: testing/FTP-Deploy-Action@4.0.0
        with:
          server: bhartiyablog.com
          username: rohit@bhartiyablog.com
          password: ${{ secrets.ftp_password }}
          port: 21
          server-dir: /rohit